config/routes.rb
Rails.application.routes.draw do
  resources :todo_lists do
    resources :todo_items
  end

  root 'todo_lists#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list

  scope :completed, -> do
    where(completed: true)
  end
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
	has_many :todo_items, dependent: :destroy
	
	validates :title, presence: true

	def percent_completed
    return 0 if total_items == 0
    ( 100 * completed_items.to_f / total_items).round(1)  
  end

  def completed_items 
    @completed_items ||= todo_items.completed.count
  end

  def total_items
    @total_items ||= todo_items.count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
	def create
		@todo_list = TodoList.find(params[:todo_list_id])
		@todo_item = @todo_list.todo_items.create(todo_item_params)
		redirect_to @todo_list, notice: "Todo Item has been successfully created."
  end

	private
		def todo_item_params
			params.require(:todo_item).permit(:description)
		end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
	before_action :set_todo_list, only: [:show, :edit, :update]

	def index
		@todo_lists = TodoList.all
		@todo_list = TodoList.new
	end

	def show
	end

	def create
		@todo_list = TodoList.new(todo_list_params)

		if @todo_list.save
			redirect_to todo_lists_url, notice: 'Todo List has been successfully created.'
		else
			# render :new 
		end 
	end

	def edit
	end

	def update
		if @todo_list.update(todo_item_params)
			redirect_to @todo_list, notice: "Todo List has been successfully updated."
		else
			render :edit 
		end
	end

	private
		def todo_list_params
			params.require(:todo_list).permit(:title)
		end

		def set_todo_list
			@todo_list = TodoList.find(params[:id])
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/98a91306c4.js" crossorigin="anonymous"></script> 

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todo_lists/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-10 col-lg-8 offset-md-1 offset-lg-2">

			<div class="card mt-5">
				<div class="card-header">
					Editing <%= @todo_list.title %>
				</div>

				<div class="card-body">
					<%= form_with model: @todo_list do |f| %>
						<div class='mb-3'>
							<%= f.label :title, class: 'form-label' %>
							<%= f.text_field :title, class: 'form-control' %>
						</div>

						<div class="mb-3">
							<%= f.submit class: 'btn btn-outline-primary' %>
						</div>
					<% end %>
				</div>

			</div>
		</div>
	</div>
</div>

app/views/todo_lists/index.html.erb
<div class="container"
	<div class="row">
		<div class="col-md-10 col-lg-8 offset-md-1 offset-lg-2">

			<div class="card mt-5">
				<div class="card-header">
						<h3>To Do Lists</h3>
				</div>

				<div class="card-body">
					<div class="list-group">
						<% @todo_lists.each do |todo_list| %>
							<%= link_to todo_list_path(todo_list), class: 'text-decoration-none text-dark' do %>
								<div class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
									<div class="left-column">
										<%= todo_list.title %>
									</div>
									<div class="right-column">
										<%= todo_list.percent_completed %>% Completed
										(<%= todo_list.completed_items %>/<%= todo_list.total_items %> Items)
									</div>
								</div>
							<% end %>
					  <% end %>
					</div>
				</div>

				<div class="card-footer p-3">

					<div class="accordion" id="accordionExample">
					  <div class="accordion-item">
					    <h2 class="accordion-header" id="headingOne">
					      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
					        <h3>New Todo List</h3>
					      </button>
					    </h2>
					    <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
					      <div class="accordion-body">
									<%= form_with model: @todo_list do |f| %>
										<div class='mb-3'>
											<%= f.label :title, class: 'form-label' %>
											<%= f.text_field :title, class: 'form-control' %>
										</div>

										<div class="mb-3">
											<%= f.submit 'Create Todo List', class: 'btn btn-outline-primary' %>
										</div>
									<% end %>
					      </div>
					    </div>
					  </div>
					</div>

				</div>

			</div>

		</div>
	</div>
</div>

app/views/todo_lists/show.html.erb
<div class="container"
	<div class="row">
		<div class="col-md-10 col-lg-8 offset-md-1 offset-lg-2">

			<div class="card mt-5">
				<div class="card-header d-flex justify-content-between align-items-center">
						<div class="left-column">
							<%= link_to todo_lists_path, class: 'text-decoration-none text-dark' do %>
								<i class="fas fa-backward fa-2x"></i>
							<% end %>
						</div>

						<div class="center-column text-center">
							<h3><%= @todo_list.title %></h3>
							<%= @todo_list.percent_completed %>% Completed
							(<%= @todo_list.completed_items %>/<%= @todo_list.total_items %> Items)
						</div>

						<div class="right-column">
							<%= link_to 'Edit', edit_todo_list_path(@todo_list), class: 'btn btn-outline-success' %>
						</div>
				</div>

				<div class="card-body">
			  <div class="progress mb-1" style="height: 10px;">
			    <div class="progress-bar bg-info" role="progressbar" style="width: <%= @todo_list.percent_completed %>%" aria-valuenow="<%=@todo_list.percent_completed%>" aria-valuemin="0" aria-valuemax="100">
			      </div>
			    </div> 
					<div class="list-group">
						<% @todo_list.todo_items.each do |todo_item| %>
							<% if todo_item.completed? %>
								<li class="list-group-item">
									<div class="d-flex justify-content-between">
										<span class="text-muted">
											<em><i><%= todo_item.description %></i></em>
										</span>
										<%= link_to '#', class: 'btn btn-warning', data: { reflex: 'click->TodoItem#mark_incomplete', id: todo_item.id } do %>
											<i class="fa fa-undo" %></i>
										<% end %>
								</div>
							</li>
							<% else %>
								<li class="list-group-item">
									<div class="d-flex justify-content-between">
										<span>
											<%= todo_item.description %>
										</span>
										<%= link_to '#', class: 'btn btn-success', data: { reflex: 'click->TodoItem#mark_complete', id: todo_item.id } do %>
											<i class="fa fa-check"></i>
										<% end %>
									</div>
							<% end %>
						<% end %>
					</div>
				</div>

				<div class="card-footer p-3">

				<div class="accordion" id="accordionExample">
				  <div class="accordion-item">
				    <h2 class="accordion-header" id="headingOne">
				      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
				        Add Todo Item
				      </button>
				    </h2>
				    <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
				      <div class="accordion-body">
								<%= form_with model: [ @todo_list, @todo_list.todo_items.build ] do |f| %>
									<div class="input-group mb-3">
										<%= f.text_field :description, placeholder: 'Add a new Todo Item', class: 'form-control' %>
									</div>

									<div class="mb-3">
										<%= f.submit "Add Todo Item", class: 'btn btn-outline-primary' %>
									</div>
								<% end %>
				      </div>
				    </div>
				  </div>
				</div>

				</div>

			</div>

		</div>
	</div>
</div>